from os import getenv
import logging

KAFKA_SERVERS = getenv('KAFKA_SERVERS')

KAFKA_MESSAGE_TOPIC = getenv('KAFKA_MESSAGE_TOPIC')
KAFKA_ANOMALY_TOPIC = getenv('KAFKA_ANOMALY_TOPIC')
KAFKA_MESSAGE_CONSUMER_GROUP = getenv('KAFKA_MESSAGE_CONSUMER_GROUP')

DBAAS_SENTINEL_ENDPOINT_SIMPLE = getenv('DBAAS_SENTINEL_ENDPOINT_SIMPLE')
DBAAS_SENTINEL_SERVICE_NAME = getenv('DBAAS_SENTINEL_SERVICE_NAME')
DBAAS_SENTINEL_PASSWORD = getenv('DBAAS_SENTINEL_PASSWORD')

LOG_COUNT = int(getenv('LOG_COUNT', 100))
LOGGING_LEVEL = int(getenv('LOGGING_LEVEL', logging.DEBUG))
REDIS_SOCKET_TIMEOUT = int(getenv('REDIS_SOCKET_TIMEOUT', 5))